cmake_minimum_required(VERSION 3.21)
include($ENV{XMOS_CMAKE_PATH}/xcommon.cmake)
project(fwk_voice_tests_adec)
if(NOT BUILD_NATIVE)
    add_subdirectory( de_unit_tests )
endif()
add_subdirectory( test_adec_profile )
add_subdirectory( test_wav_adec )
add_subdirectory( test_adec )
add_subdirectory( test_adec_startup )
add_subdirectory( test_delay_estimator )
