cmake_minimum_required(VERSION 3.21)
include($ENV{XMOS_CMAKE_PATH}/xcommon.cmake)
project(fwk_voice_tests)

add_subdirectory(lib_agc)
add_subdirectory(lib_ns)
add_subdirectory(lib_ic)
add_subdirectory(lib_vnr)
add_subdirectory(lib_aec)
add_subdirectory(lib_adec)
if(NOT BUILD_NATIVE)
    add_subdirectory( pipeline )
endif()
